### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by mateorico** [sparkfun/MPU-9250_Breakout#10]
Hi, 

I'm trying to compiling the source code using platformio but always got errors. I have installed the library using  the Library Manager. There is any way to do that?

**Comment by santaimpersonator** [comment]
Unfortunately, we do not support platformio. I suggest using the Arduino IDE as mentioned in our [hookup guide](https://learn.sparkfun.com/tutorials/mpu-9250-hookup-guide). Otherwise, you may need to [contact platformio](https://platformio.org/support) for how to adapt Arduino libraries to their development platform.
