### ISSUE TITLE
Magnetometer Calibration

### ISSUE THREAD

**Issue by andresespinosapc** [sparkfun/MPU-9250_Breakout#7]
I have read that calibrating the magnetometer is very important for its precision. I see that you removed the magnetometer calibration (magcalMPU9250 function) from the original code, is there a particular reason to do that?

**Comment by mtmccrea** [comment]
I've had some success integrating Paul Stoffregen's [Mahony](https://github.com/PaulStoffregen/MahonyAHRS) and [Madgwick](https://github.com/PaulStoffregen/MadgwickAHRS) filters (conveniently implemented as Arduino libraries), though they do require inputting some calibration data, which you can get using his [MotionCal](https://www.pjrc.com/store/prop_shield.html) software.  If I get this to be a bit more streamlined with the MPU-9250, I'll post a workflow... unless the SF folks beat us to it ;)

**Comment by brunocannavina** [comment]
Do you have the code to calibrate de MPU9250 with motioncal?
I don't know what data tipe Motioncal expect! I can´t find that info nowhere

**Comment by mtmccrea** [comment]
It's been a while since I looked at this, but I see that I have a modified firmware file for the MPU9250 that just sends the raw data values to the over the serial port in a format that MotionCal expects. 
https://github.com/mtmccrea/headtracker/blob/85296f0c8f2a53cfb9db11257ff2cd7ae64d1a08/arduino/mpu9250_imu_sendRawSensorData/mpu9250_imu_sendRawSensorData.ino#L176

You can give it a try:
https://github.com/mtmccrea/headtracker/blob/master/arduino/mpu9250_imu_sendRawSensorData/mpu9250_imu_sendRawSensorData.ino

Hope this helps.

**Comment by santaimpersonator** [comment]
Looks like [mtmccrea](https://github.com/mtmccrea) has a working solution, I am closing this issue for now. Please feel free to reopen this issue in the [DMP library](https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library) if need. That being said, the MPU-9250 is currently marked for EOL, so we may not get to creating that feature.
